import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  RefreshControl,
  TouchableOpacity,
  Alert,
  Button,
  ActivityIndicator
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { db, auth } from './firebaseConfig';
import {
  collection,
  query,
  where,
  onSnapshot,
  orderBy,
  updateDoc,
  deleteDoc,
  doc,
  addDoc,
  serverTimestamp,
} from 'firebase/firestore';

export default function NotificationsScreen() {
  const [notifications, setNotifications] = useState([]);
  const [refreshing, setRefreshing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchNotifications = async () => {
      try {
        const uid = auth.currentUser?.uid;
        if (!uid) {
          setError('User not authenticated');
          setLoading(false);
          return;
        }

        console.log('Fetching notifications for user:', uid);
        
        const q = query(
          collection(db, 'notifications'),
          where('userId', '==', uid),
          orderBy('timestamp', 'desc')
        );

        const unsubscribe = onSnapshot(
          q,
          (snapshot) => {
            console.log('Received snapshot with', snapshot.docs.length, 'documents');
            const data = snapshot.docs.map((doc) => {
              const docData = doc.data();
              console.log('Document data:', docData);
              return {
                id: doc.id,
                ...docData,
                // Ensure timestamp is properly handled
                timestamp: docData.timestamp?.toDate?.() || docData.timestamp
              };
            });
            setNotifications(data);
            setLoading(false);
            setError(null);
          },
          (error) => {
            console.error('Firestore error:', error);
            setError('Failed to load notifications');
            setLoading(false);
          }
        );

        return unsubscribe;
      } catch (error) {
        console.error('Error in fetchNotifications:', error);
        setError('An unexpected error occurred');
        setLoading(false);
      }
    };

    fetchNotifications();
  }, []);

  const onRefresh = async () => {
    setRefreshing(true);
    // Simulate refresh delay
    setTimeout(() => {
      setRefreshing(false);
    }, 1000);
  };

  const markAsRead = async (notificationId) => {
    try {
      await updateDoc(doc(db, 'notifications', notificationId), {
        read: true,
      });
    } catch (error) {
      console.log('Error marking notification as read:', error);
      Alert.alert('Error', 'Could not mark notification as read.');
    }
  };

  const deleteNotification = async (notificationId) => {
    try {
      await deleteDoc(doc(db, 'notifications', notificationId));
    } catch (error) {
      console.log('Error deleting notification:', error);
      Alert.alert('Error', 'Could not delete notification.');
    }
  };

  const handleLongPress = (item) => {
    Alert.alert(
      'Delete Notification?',
      `Are you sure you want to delete "${item.title}"?`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: () => deleteNotification(item.id),
        },
      ]
    );
  };

  const addSampleNotification = async () => {
    const uid = auth.currentUser?.uid;
    if (!uid) {
      Alert.alert('Not logged in', 'Please log in to add notifications.');
      return;
    }

    try {
      await addDoc(collection(db, 'notifications'), {
        userId: uid,
        title: 'Sample Notification',
        body: 'This is a test notification generated by the app.',
        read: false,
        timestamp: serverTimestamp(),
      });
      console.log('Sample notification added successfully');
    } catch (error) {
      console.error('Error adding notification:', error);
      Alert.alert('Error', 'Failed to add sample notification.');
    }
  };

  const renderItem = ({ item }) => (
    <TouchableOpacity
      onPress={() => !item.read && markAsRead(item.id)}
      onLongPress={() => handleLongPress(item)}
      activeOpacity={0.7}
    >
      <View
        style={[
          styles.notificationCard,
          !item.read && styles.unreadNotification,
        ]}
      >
        <View style={styles.iconRow}>
          <Ionicons
            name={
              item.title?.toLowerCase().includes('ride')
                ? 'car-outline'
                : 'notifications-outline'
            }
            size={20}
            color="#FFA500"
            style={{ marginRight: 8 }}
          />
          <Text style={styles.title}>{item.title}</Text>
        </View>
        <Text style={styles.body}>{item.body}</Text>
        {item.timestamp && (
          <Text style={styles.timestamp}>
            {new Date(item.timestamp).toLocaleString()}
          </Text>
        )}
      </View>
    </TouchableOpacity>
  );

  if (loading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator size="large" color="#FFA500" />
        <Text style={styles.loadingText}>Loading notifications...</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.errorText}>{error}</Text>
        <Button
          title="Retry"
          onPress={() => {
            setLoading(true);
            setError(null);
            setNotifications([]);
          }}
          color="#FFA500"
        />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <Text style={styles.header}>Notifications</Text>

      <Button
        title="Add Sample Notification"
        onPress={addSampleNotification}
        color="#FFA500"
      />

      {notifications.length === 0 ? (
        <View style={styles.centerContainer}>
          <Text style={styles.emptyMessage}>No notifications yet.</Text>
          <Text style={styles.emptySubtext}>Pull down to refresh</Text>
        </View>
      ) : (
        <FlatList
          data={notifications}
          keyExtractor={(item) => item.id}
          renderItem={renderItem}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={onRefresh}
              tintColor="#FFA500"
            />
          }
          contentContainerStyle={{ paddingBottom: 20 }}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    padding: 16,
  },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFA500',
    marginBottom: 12,
    textAlign: 'center',
  },
  notificationCard: {
    backgroundColor: '#2a2a2a',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
  },
  unreadNotification: {
    borderLeftWidth: 4,
    borderLeftColor: '#FFA500',
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  title: {
    color: '#FFA500',
    fontSize: 16,
    fontWeight: '600',
  },
  body: {
    color: '#ccc',
    fontSize: 14,
    marginTop: 4,
  },
  timestamp: {
    fontSize: 12,
    color: '#888',
    marginTop: 6,
  },
  emptyMessage: {
    color: '#888',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
  },
  emptySubtext: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#FFA500',
    marginTop: 16,
  },
  errorText: {
    color: 'red',
    fontSize: 16,
    marginBottom: 16,
    textAlign: 'center',
  },
});